### ISSUE TITLE
Versioning incorrect

### ISSUE THREAD

**Issue by FluffyPuppyKasey** [GabrielDja/GD-CraftsEnhanced#1]
Hi there! I wanted to install the mod for 24w09a but it seems like the version actually reports itself as 1.20.5-alpha.24.9.a rather than 24w09, leading to an error when trying to load the game with the mod installed
![image](https://github.com/GabrielDja/GD-CraftsEnhanced/assets/58578837/7efa2177-c80c-4aaf-947b-5fa08110ec97)

**Comment by GabrielDja** [comment]
Hello,
Thank you for letting me know. This problem has been corrected and will be updated within 24 hours :D

**Comment by FluffyPuppyKasey** [comment]
> Hello, Thank you for letting me know. This problem has been corrected and will be updated within 24 hours :D

You're welcome!
